### ISSUE TITLE
Won't locate Cast

### ISSUE THREAD

**Issue by NorthShoreGuy** [googlecast/CastHelloVideo-chrome#1]
I have upgraded Chrome, got the new browser extension, downloaded this code, checked that the Cast is at current release, and this application when loaded in Chome gives the following in the log text element:

"init success"
"receiver list empty"
I have adjusted the JS to an app ID I have for my own receiver and the same results. 
I can cast from the browser (i.e. cast Chrome tab) successfully, so the extension and cast are working.

**Comment by Owlz** [comment]
Re-installing the cast extension did it for me. I'm guessing that's the root of this problem and Canary is simply an extended way to refresh your Chrome Cast extension.

For what it's worth, an indicator of strange things happening to me was seeing duplicate entries for the chromecast in the casting button.

**Comment by entertailion** [comment]
Cast is now built into the Chrome browser.
