### ISSUE TITLE
Module initialization will not run if the cast API is available at startup

### ISSUE THREAD

**Issue by sergiogiogio** [googlecast/CastHelloVideo-chrome#11]
Module initialization will not run if the cast API is available at startup.
In practice I assume there's always a delay so the initialization does run but it would be make it more robust (e.g. using similar technique to CastVideos example).

```
if (!chrome.cast || !chrome.cast.isAvailable) {
  setTimeout(initializeCastApi, CAST_API_INITIALIZATION_DELAY);
}
```

**Comment by entertailion** [comment]
Please use the latest Cast Chrome sender SDK and use this initialization:
<script>
window['__onGCastApiAvailable'] = function(isAvailable) {
  if (isAvailable) {
    initializeCastApi();
  }
};
</script>
