### ISSUE TITLE
unable to cast from rtmp:// mp4 video file that JWPlayer plays and recasts just fine

### ISSUE THREAD

**Issue by rob613** [googlecast/CastHelloVideo-chrome#12]
This software provides some information about a media error, which is better than other silent errors I've been seeing trying other ways to chromecast a particular video, or any of a set of videos, that are available at a particular video library I frequent.  When I play the video through JWPlayer on my Android smart phone I can fairly easily coax it to send the video stream onto my Chromecast into a TV. When I play it on a Google Chrome browser running JWPlayer on a desktop computer I cannot get the video to chromecast.  Using this software or other browser software (not sure if it is a sender or a receiver) it silently fails.   I believe that the Media Error message I get when I deploy this software onto an external web server and use it from desktop Chrome browser gives some information.  Ultimately I think it is just a bug in the chromecast that it refuses to accept the video stream over rtmp:// prefix even though it is MP4 and a supported video format.  If JWPlayer can do it, surely Chromecast should.  I am entering this as a bug report here so that Google staff who either contribute to this project or refer to this project to explain the Chromecast SDK may see it.  Of course if there is a fix for the problem found and this project solves it, even better.

**Comment by pengying** [comment]
Not an issue with Cast. I don't think Chrome supports native RTMP.  I thought RTMP was Flash based?  So you would have to be running flash on the receiver which is probably too much for the Cast hardware.

Why not use HTTP?

**Comment by rob613** [comment]
In this case it is mp4 video served by rtmp, and the server will not
respond to an http request.
